version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      # - image: arvindr226/alpine-ssh
      - image: circleci/node
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ea:d0:71:22:0c:01:02:73:d7:d2:79:5a:27:21:7b:85"
      - checkout

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "package.json" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-

      # - run:
      #     name: Run and build
      #     command: |
      #       npm i
      #       unset CI
      #       npm run build

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}

      # todo check have pull
      - run: cat /home/circleci/.ssh/id_rsa
      - run: cat /home/circleci/.ssh/id_rsa.pub
      - run: 
          name: Git pull
          command: |
              ssh -o StrictHostKeyChecking=no -v $USER@$IP 'bash -i -c "cd www && git pull"'

      - run: 
          name: Build
          command: |
              ssh -o StrictHostKeyChecking=no -v $USER@$IP 'bash -i -c "cd www && npm run build"'
      

      # copy dist files to digitalocean
      # - run: 
      #     name: Copy files
      #     command: scp -o StrictHostKeyChecking=no -v -r -i ./build/* $USER@$IP://home/$USER/web

      
      - run: 
          name: Restart pm2
          command: |
            ssh -o StrictHostKeyChecking=no -v $USER@$IP 'bash -i -c "pm2 restart app"'

      # - run: ssh -o StrictHostKeyChecking=no -v $USER@$IP "bash ./deploy.sh"
      

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - main

